version: '3.8'

services:
  blog-redis:
    image: redis:latest
    ports:
      - "6380:6379"
    volumes:
      - ./d–∞ta:/root/redis
      - ./redis.conf:/usr/local/etc/redis/redis.conf
    environment:
      - REDIS_PASSWORD=my-password
      - REDIS_PORT=6379
      - REDIS_DATABASES=16
