spring:
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        default_schema: ${DB_SCHEMA}
    hibernate:
      ddl-auto: validate
    show-sql: 'false'
    open-in-view: 'false'
  application:
    name: config-server
  profiles:
    active: jdbc
  datasource:
    password: ${DB_PASSWORD}
    driver-class-name: org.postgresql.Driver
    username: ${DB_USERNAME}
    url: ${DB_URL}
    hikari:
      schema: ${DB_SCHEMA}
  cloud:
    config:
      server:
        jdbc:
          sql: SELECT key, value FROM ${DB_SCHEMA}.ms_properties prop WHERE (application=?
            OR application='all-services')  AND profile=? AND label=?
server:
  port: ${PORT}
